# https://developer-docs.netscaler.com/en-us/adc-nitro-api/current-release/configuration/ssl/sslcertkey_sslvserver_binding
- name: "vserver binding {{ nitro_vservername }} to {{ nitro_certkey }} {{ nitro_action }}"
  delegate_to: localhost
  community.network.netscaler_nitro_request:
    nsip: "{{ nitro_ip }}"
    nitro_user: "{{ nitro_username }}"
    nitro_pass: "{{ nitro_password }}"
    operation: action
    action: "{{ nitro_action }}" #add or delete to unbind
    #resource: sslcertkey_sslvserver_binding
    resource: sslvserver_sslcertkey_binding
    #name: "{{  }}"
    validate_certs: "{{ nitro_validate_certs | default(False) }}"
    attributes:
      vservername: "{{ nitro_vservername }}"
      certkeyname: "{{ nitro_certkey }}"
      snicert: "{{ nitro_snicert | default('false') }}"
  failed_when: nitro_request_output.nitro_message != "Success"
  changed_when: nitro_request_output.nitro_message == "Success"
  register: nitro_request_output

