- name: Initial setup
  hosts: localhost
  gather_facts: true
  collections:
    - community.network
    - ab.beyondtrust_secrets
  vars_files:
    - "vars/all.yml"
    - "vars/{{ awxenvironment | default('staging') }}.yml"
    - "operational_files/{{ operational_filename }}.yml"
  tasks:
    - name: "Do {{ operation }} workflow"
      include_role:
        name: "{{ operation }}"
