# https://developer-docs.netscaler.com/en-us/adc-nitro-api/current-release/configuration/ssl/sslcertlink
- name: "Link {{ nitro_ssl_certkey }} to {{ nitro_ssl_ca_name }}"
  delegate_to: localhost
  community.network.netscaler_nitro_request:
    nsip: "{{ netscaler_hostname }}"
    nitro_user: "{{ netscaler_username }}"
    nitro_pass: "{{ netscaler_password }}"
    operation: action
    action: link
    resource: sslcertkey 
    #name: "{{ nitro_file_upload_name }}"
    validate_certs: "{{ nitro_validate_certs | default(False) }}"
    attributes:
      certkey: "{{ nitro_ssl_certkey }}"
      linkcertkeyname: "{{ nitro_ssl_ca_name }}"
      #snicert ?
#  failed_when: nitro_request_output.nitro_message != ""
#  changed_when: nitro_request_output.nitro_message == "OK (0 bytes)"
  register: nitro_request_output

